FROM python:3.5-slim-stretch

LABEL author.name="Shin Yang" \
      author.email="ityoung@foxmail.com" \
      version="0.1" \
      description="Dockerfile Template of Updating Debian."

RUN sed -i 's/deb.debian.org/ftp.cn.debian.org/g' /etc/apt/sources.list \
  && sed -i 's/security.debian.org/ftp.cn.debian.org/g' /etc/apt/sources.list \
  && apt-get update -y \
  && apt-get install -y vim \
  && apt-get clean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
